name: ClientDetector
version: '${project.version}'
authors: [ Sportkanone123, Loving11ish ]
main: de.sportkanone123.clientdetector.spigot.ClientDetector
description: A simple plugin to detect and manage a player's client/mods
load: POSTWORLD
api-version: 1.13
folia-supported: true

softdepend: [PlaceholderAPI, ProtocolLib, ViaVersion]

commands:
  clientdetector:
    description: The main command that accesses all other commands for the plugin.
    permission: clientdetector.command
    aliases:
      - cd
  client:
    description: The command to access the client based commands.
    permission: clientdetector.command
  forge:
    description: The command to access the Forge based commands.
    permission: clientdetector.command
  mods:
    description: The command to access the mods based commands.
    permission: clientdetector.command

permissions:
  clientdetector.*:
    default: op
    children:
      clientdetector.command:
        default: op
      clientdetector.bypass:
        default: op
      clientdetector.notify:
        default: op
      clientdetector.update:
        default: op